version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: dbothwell
          password: 59160e01-2308-487e-a00c-81c7613da799  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  build-android:
    docker:
      - image: cimg/android:2021.10.2
        auth:
          username: dbothwell
          password: 59160e01-2308-487e-a00c-81c7613da799  # context / project UI env-var reference
